server:
    port: 9090
spring:
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true


  h2:
    console:
      enabled: true
      path: /h2_db
  datasource:
    url: jdbc:h2:file:~/tistoryDb/testdb;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: kim
    password: 1234
